<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta name="viewport" content="width=device-width , initial-scale=1">
        <title> Visite de la Galerie </title>
        <meta name="description" content="Suite à un projet de fin d'année, nous avons décider de créer un e-commerce."/>
        <meta name="keywords" content="Magento, Varien, E-commerce"/>
        <meta name="robots" content="INDEX,FOLLOW"/>
        <link rel="icon" href="http://magento.cccomputer.fr/skin/frontend/default/modern/favicon.ico" type="image/x-icon"/>
        <link rel="shortcut icon" href="http://magento.cccomputer.fr/skin/frontend/default/modern/favicon.ico" type="image/x-icon"/>
        <link rel="stylesheet" type="text/css" href="http://magento.cccomputer.fr/skin/frontend/default/modern/css/L3Q2/gallery.css" media="all"/>
        <link rel="stylesheet" type="text/css" href="http://magento.cccomputer.fr/skin/frontend/default/modern/css/L3Q2/jquery.mobile-1.3.1.min.css" media="all"/>
        <link rel="stylesheet" type="text/css" href="http://magento.cccomputer.fr/skin/frontend/default/modern/css/print.css" media="print"/>        
    </head>
    <body>
        <?php echo $this->getChildHtml('content') ?>
    </body>
</html>