<div id="page">
    <div data-role="header">
        <h1>Comment se deplacer<h1>
    </div>
    <div data-role="content" id="container">
        <div data-role="page" data-url="howtomove.html">
            <div data-role="header">
                <h4> Utilisateur sur PC </h4>
            </div>
            <div data-role="content"> 
                <p>	
                    Flèche du haut ou la touche "A" : avancer
                    <br> Flèche du bas ou la touche "S" : reculer
                    <br> Flèche de gauche ou la touche "Q" : rotation vers la gauche
                    <br> Flèche de droite ou la touche "D" : rotation vers la droite
                    <br>
                    <br> Pour bouger avec la souris il suffit de déplacer la souris sur les zones indiquer ci dessous
                </p>
                <h4> Utilisateur sur mobile ou tablette </h4>
                <p>
                    Pour se deplacer il suffit de toucher les zones suivantes :<br>
                    <img src="<?php echo $this->getSkinUrl() ?>/images/L3Q2/mvttuto.pgn" border="0" />
                </p>
            </div>
        </div>
    </div>
    <div data-role="footer">    
    </div>
</div>